#!/bin/sh
#get sendTo, subject, body from zabbix
sendTo=$1
subject=$2
body=$3
# {'hostgroupName': 'SeasideConsulting_GW01C821', 'topic': 'WSN_GW_01C821.WEB.SCAN_PROBLEM'}}
hostgroupName=`echo $body | sed -n 's/.*"hostgroupName".*"\([^"]*\)".*/\1/p'`
#Extract topic from hostgroupName
GWUID=`echo $hostgroupName | sed -n 's/.*_GW\(.*\)/\1/p'`
#Generate topic from GWUID
topic="WSN_GW_${GWUID}.WEB.SCAN_PROBLEM"

#send mail
message='{
  "uid": "SIO_EXCTL_'${RANDOM}'",
  "message": {
    "method": "problem.get",
    "params": {
      "topic": "'${topic}'",
      "hostgroupName": "'${hostgroupName}'",
      "body": '${body}'
    }
  }
}'

mosquitto_pub -h wsnCluster_mqtt -p 1885 -u mqtt_broker -P !Da#ImU%VuF3V -t "ZABBIX_AGENT_PUBLISH" -m "$message"
