#!/bin/sh
#get sendTo, subject, body from zabbix
sendTo=$1
subject=$2
body=$3
topic=`echo $body | sed -n 's/.*"topic": "\([^"]*\)".*/\1/p'`
hostgroupName=`echo $body | sed -n 's/.*"hostgroupName": "\([^"]*\)".*/\1/p'`

#send mail
message='{
  "uid": "SIO_EXCTL_'${RANDOM}'",
  "message": {
    "method": "problem.get",
    "params": {
      "topic": "'${topic}'",
      "hostgroupName": "'${hostgroupName}'"
    }
  }
}'

mosquitto_pub -h wsnCluster_mqtt -p 1885 -u mqtt_broker -P !Da#ImU%VuF3V -t "ZABBIX_AGENT_PUBLISH" -m "$message"
